package com.Game.enumerations;

public enum GuiSpriteType {
    EMPTY_GEM, FULL_HP_GEM, HALF_HP_GEM, FULL_ENERGY_GEM, HALF_ENERGY_GEM, FULL_MANA_GEM, HALF_MANA_GEM, AGREE, DISAGREE, INV_SLOT_RIGHT, INV_SLOT_LEFT,
    EQUIP_SLOT_BIG, EQUIP_SLOT_SMALL, REST, MENU, MAP, TURN_LEFT, FORWARD, TURN_RIGHT, STRAFE_LEFT, BACKWARD, STRAFE_RIGHT,
    ACTION_1, ACTION_2, EVENT_BAR, ENEMY_BAR, DARK_CHARACTER, LIGHT_CHARACTER, DARK_SPELLBOOK, LIGHT_SPELLBOOK, STATS_PRIMARY, STATS_SECONDARY,
    EQUIPMENT, SPELLBOOK, SECONDARY_STATS_LIGHT, PRIMARY_STATS_DARK, SECONDARY_STATS_DARK, PRIMARY_STATS_LIGHT, INVENTORY
}
