package com.Game.enumerations;

public enum SpriteType {
    RED_POTION_BIG, RED_POTION_SMALL, 
    BLUE_POTION_BIG, BLUE_POTION_SMALL, EMPTY_POTION_BIG, 
    EMPTY_POTION_SMALL, SWORD_IRON, SWORD_GOLD, SWORD_SAPPHIRE,
    SWORD_FLAMING, DAGGER_IRON, AXE_IRON_ONE_BLADED, AXE_IRON_TWO_BLADED,
    HAMMER_IRON, SHIELD_WOODEN_TOWER, SHIELD_WOODEN_ROUND, SHIELD_IRON_KITE,
    SHIELD_IRON_TOWER, WAND_WOODEN, WAND_RUBY, WAND_SAPPHIRE, STAFF_WOODEN,
    KEY_IRON, KEY_GOLDEN, RING_IRON, RING_GOLDEN, RING_GEM_EMERALD
}
